- name: copy prometheus set up configuration
  ansible.builtin.template:
    src : prometheus.yml
    dest: /opt/prometheus/prometheus.yml


- name: restart the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
