- name: copy prometheus set up configuration
  ansible.builtin.template:
    src : prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy prometheus record file
  ansible.builtin.template:
    src : record.yml
    dest: /opt/prometheus/record.yml

- name: copy prometheus alerts file
  ansible.builtin.template:
    src : alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: restart the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: copy alert manager conf
  ansible.builtin.template:
    src : alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
