groups:
 - name: infra_alerts
   rules:
   - alert: serverDownAlert
     expr: up == 0
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: server Down alert

   - alert: BackendserviceDownAlert
     expr: node_systemd_unit_state{exported_name="backend.service",state="active"} == 0
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: Backendservice Down alert

   - alert: frontendserviceDownAlert
     expr: node_systemd_unit_state{exported_name="frontend.service",state="active"} == 0
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: frontendservice Down alert

   - alert: mysqlserviceDownAlert
     expr: node_systemd_unit_state{exported_name="mysqld.service",state="active"} == 0
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: mysqlservice Down alert

   - alert: High cpu usage
     expr: 100 - (avg by (name) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: High cpu usage alert

   - alert: High memory usage
     expr: 100 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100) > 80
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: High memory usage alert